# Generated by Django 3.2.23 on 2023-11-14 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20231114_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
