# Generated by Django 3.2.23 on 2023-11-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_reservation_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='party_size',
        ),
        migrations.AddField(
            model_name='reservation',
            name='batter',
            field=models.CharField(choices=[('N', 'Nuts'), ('V', 'Vanilla'), ('B', 'Buttery'), ('R', 'Red Velvet')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='filling',
            field=models.CharField(choices=[('BR', 'Brigadier'), ('BW', 'Brigadeiro with walnuts'), ('FM', '4 Milk'), ('RF', 'Red fruits'), ('CC', 'Coconut'), ('MC', 'Milk cream')], default='BR', max_length=2),
        ),
        migrations.AddField(
            model_name='reservation',
            name='size',
            field=models.CharField(choices=[('S', 'Small - 1 layer x 24cm'), ('M', 'Medium - 2 layers x 20cm'), ('L', 'Large - 3 layers x 20cm'), ('XL', 'Extra Large - 3 layers x 24cm')], default='S', max_length=2),
        ),
    ]
