# Generated by Django 4.2.7 on 2023-11-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_reservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='batter',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
