# Generated by Django 4.2.7 on 2023-11-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_reservation_batter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='batter',
        ),
    ]
