# Generated by Django 4.2.7 on 2023-11-19 23:08

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_reservation_batter'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE booking_reservation DROP COLUMN IF EXISTS filling CASCADE;",
            reverse_sql="ALTER TABLE booking_reservation ADD COLUMN filling varchar(255) NOT NULL;",
        ),
    ]
