# Generated by Django 4.2.7 on 2023-11-19 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_filling_field'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE booking_reservation DROP COLUMN IF EXISTS size CASCADE;",
            reverse_sql="ALTER TABLE booking_reservation ADD COLUMN size varchar(255) NOT NULL;",
        ),
    ]
