# Generated by Django 4.2.7 on 2023-11-19 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_size_field'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE booking_reservation DROP COLUMN IF EXISTS is_customized CASCADE;",
            reverse_sql="ALTER TABLE booking_reservation ADD COLUMN is_customized boolean NOT NULL;",
        ),
    ]
