# Generated by Django 4.2.7 on 2023-11-20 09:05

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_is_customized_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='booking.order'),
        ),
    ]
