# Generated by Django 4.2.7 on 2023-11-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_order_created_at_remove_order_quantity_and_more'),
    ]

    operations = [
    ]
